# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3cb113feeb9626e0eec2f03484d59f1f3496e6606b37afd01f82d85799caf0f8d294eced0b6943a9be492f73aad0c2fca6839257f46892b1ce92eb55eeccc31

test:
  secret_key_base: 372d575ed060e9037908f7c2ada2f0fbfcf47f5e0e998fad178c5d61b0e57e3f1c4688f123ce7ed04292fce528c59760d7f5503ebe269a737736b6a457e710be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
